### ISSUE TITLE
Timer isnt working

### ISSUE THREAD

**Issue by gamerrrrrraaaa** [Stachelbeere1248/zombies-utils#2]
I can get the SLA mod to work but i cant seem to get the timer/autosplit to work. is there something i need to do to toggle it on or something? is it maybe not compatible with my version (1.8.9)?

**Comment by Stachelbeere1248** [comment]
hello @gamerrrrrraaaa,
are you in-game when it doesn't work? did you start a game?

**Comment by gamerrrrrraaaa** [comment]
> hello @gamerrrrrraaaa, are you in-game when it doesn't work? did you start a game?

Yeah it just doesn't work at all for me regardless of whether I'm in game or not. Nothing at all shows up.
Could the problem be that other mods are preventing it from working?

**Comment by Stachelbeere1248** [comment]
Actually, the versions 1.2.1 and 1.2.2 both seem to have a certain bug that will be fixed in the next release. For now I recommend using v1.2.0.

**Comment by gamerrrrrraaaa** [comment]
> Actually, the versions 1.2.1 and 1.2.2 both seem to have a certain bug that will be fixed in the next release. For now I recommend using v1.2.0.

I have realised the issue is that it's not compatible with a ghost client I have called "Hydrogen". Would you by any chance know why this is? Just curious

**Comment by Stachelbeere1248** [comment]
I just found it being incompatible with SST, presumably because that overwrites some vanilla code. My mod has some basic SST feature included (the spawntimes without aa coloring), but it is up to you to chose which to use.
