### ISSUE TITLE
upload to modrinth

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Stachelbeere1248/zombies-utils#3]
I use prism launcher (and sometimes modrinth launcher) which both let me download and update mods directly from modrinth. it would be cool if the mod was available on modrinth so i could automatically update it along with all my other mods

https://modrinth.com

**Comment by Stachelbeere1248** [comment]
prismlauncher is goated, will do

**Comment by Stachelbeere1248** [comment]
it will be available [here](https://modrinth.com/mod/zombies-utils), not sure if it has to pass a review first.

**Comment by MicrocontrollersDev** [comment]
yes, there's a (usually) 2 day review (unless they are overwhelmed with submissions then it can be a bit longer). this long review process is only for the initial upload, all future releases wont have this. regardless, thanks!
