### ISSUE TITLE
When the round start,server will kick me out.

### ISSUE THREAD

**Issue by milkteanottea** [Stachelbeere1248/zombies-utils#4]
![image](https://github.com/user-attachments/assets/073d550d-42f6-4b8c-b47a-19ad4a806d00)
chatgpt translate:The file name, directory name, or volume label syntax is incorrect.

**Comment by Stachelbeere1248** [comment]
Hello, I have been inactive on this project for a while. Does this issue still persist? What operating system are you using? Can you try creating the folder `zombies` with the folders `splits` and `runs` inside manually? (located in your `.minecraft`, or whatever game directory you are using)
Also if you could please give me a log.

**Comment by milkteanottea** [comment]
Em,I have stop playing zombie for a while,so I didn't actually know what
the issue is happen now.

Stachelbeere1248 ***@***.***> 於 2024年12月14日 週六 上午12:12寫道：
